# Generated by Django 3.0.7 on 2020-11-23 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201026_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_color', models.CharField(default='#30363C', max_length=7)),
                ('title_background_color', models.CharField(default='#30363C', max_length=7)),
                ('description_background_color', models.CharField(default='#30363C', max_length=7)),
                ('button_background_color', models.CharField(default='#30363C', max_length=7)),
                ('button_text_color', models.CharField(default='#30363C', max_length=7)),
                ('text_color', models.CharField(default='#30363C', max_length=7)),
                ('post_background_color', models.CharField(default='#30363C', max_length=7)),
            ],
        ),
    ]
