# Generated by Django 3.2.3 on 2021-05-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_profile_custom_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customcolor',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
