# Generated by Django 3.2.3 on 2021-06-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_customcolor_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowerRelation',
        ),
    ]
