# Generated by Django 3.0.6 on 2020-09-15 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_positivepoint'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PositivePoint',
        ),
    ]
