# Generated by Django 3.0.6 on 2020-10-21 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_comment_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='sub_community',
        ),
    ]
