# Generated by Django 3.0.6 on 2020-10-21 14:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0010_comment_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='down_vote',
            field=models.ManyToManyField(blank=True, related_name='c_down_vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='up_vote',
            field=models.ManyToManyField(blank=True, related_name='c_up_vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='down_vote',
            field=models.ManyToManyField(blank=True, related_name='p_down_vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='up_vote',
            field=models.ManyToManyField(blank=True, related_name='p_up_vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
