# Generated by Django 3.0.6 on 2020-10-29 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0018_auto_20201029_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view',
            name='user',
        ),
        migrations.AddField(
            model_name='view',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
