# Generated by Django 3.0.6 on 2020-10-29 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0019_auto_20201029_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='new_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='view',
            name='old_timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
