# Generated by Django 3.0.6 on 2020-11-03 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0021_remove_view_new_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.PostType'),
        ),
    ]
