# Generated by Django 3.0.6 on 2020-11-05 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0025_commentpoint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentpoint',
            options={'ordering': ['-point']},
        ),
    ]
