# Generated by Django 3.0.6 on 2020-11-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0027_postpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='point',
            field=models.FloatField(default=0),
        ),
    ]
