# Generated by Django 3.0.7 on 2020-11-06 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0028_post_point'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-point']},
        ),
    ]
