# Generated by Django 3.0.7 on 2020-11-06 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0029_auto_20201106_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='rule',
            field=models.TextField(blank=True),
        ),
    ]
