# Generated by Django 3.0.7 on 2020-11-06 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0030_post_rule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='rule',
        ),
    ]
