# Generated by Django 3.0.7 on 2020-11-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0031_remove_post_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='point',
            field=models.FloatField(default=0),
        ),
    ]
