# Generated by Django 3.0.7 on 2020-11-07 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0032_comment_point'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-point']},
        ),
    ]
