# Generated by Django 3.0.7 on 2020-11-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0033_auto_20201107_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
