# Generated by Django 3.0.7 on 2020-11-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0034_comment_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='state',
            field=models.CharField(default='public', max_length=10, null=True),
        ),
    ]
