# Generated by Django 3.0.7 on 2021-04-08 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0037_auto_20201123_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('dislike', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('view', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('like', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('share', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='vote',
            field=models.ManyToManyField(blank=True, to='post.UserVote'),
        ),
    ]
