# Generated by Django 3.2.3 on 2021-05-30 08:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0036_auto_20201120_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='hidden_in_community',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('dislike', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('view', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('like', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('share', models.IntegerField(choices=[(0, 0), (1, 1)], default=0)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
