# Generated by Django 3.2.3 on 2021-05-30 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0040_post_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posttype',
            options={'ordering': ['-id']},
        ),
    ]
