# Generated by Django 3.0.7 on 2021-05-15 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0034_auto_20210507_1918'),
        ('post', '0040_post_hidden_in_community'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hidden_in_community',
        ),
        migrations.AddField(
            model_name='post',
            name='hidden_in_community',
            field=models.ManyToManyField(blank=True, related_name='hidden_in_coomunity', to='community.Community'),
        ),
    ]
