# Generated by Django 3.0.7 on 2021-05-15 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0041_auto_20210516_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='hidden_in_community',
        ),
        migrations.AddField(
            model_name='post',
            name='hidden_in_community',
            field=models.BooleanField(default=False),
        ),
    ]
