# Generated by Django 3.2.3 on 2021-05-30 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0041_alter_posttype_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.posttype'),
        ),
    ]
