# Generated by Django 3.2.3 on 2021-05-30 11:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0042_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='down_vote',
            field=models.ManyToManyField(blank=True, null=True, related_name='p_down_vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='up_vote',
            field=models.ManyToManyField(blank=True, null=True, related_name='p_up_vote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
