# Generated by Django 3.2.3 on 2021-06-12 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0045_rename_timestamp_post_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='timestamp',
        ),
    ]
