# Generated by Django 3.0.6 on 2020-09-14 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0002_auto_20200914_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('community_type', models.CharField(blank=True, max_length=255, null=True)),
                ('post', models.ManyToManyField(blank=True, to='post.Post')),
            ],
        ),
        migrations.CreateModel(
            name='SubCommunity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('community_type', models.CharField(max_length=255, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='community.Community')),
                ('post', models.ManyToManyField(blank=True, to='post.Post')),
            ],
        ),
    ]
