# Generated by Django 3.0.6 on 2020-10-05 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0005_auto_20200915_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='post',
        ),
    ]
