# Generated by Django 3.0.6 on 2020-10-05 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0006_remove_community_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcommunity',
            name='post',
        ),
    ]
