# Generated by Django 3.0.6 on 2020-10-23 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0009_auto_20201021_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.Community'),
        ),
    ]
