# Generated by Django 3.0.6 on 2020-10-28 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0010_auto_20201023_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
