# Generated by Django 3.0.6 on 2020-11-02 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0013_auto_20201102_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
