# Generated by Django 3.0.7 on 2020-11-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_auto_20201102_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='rule',
            field=models.TextField(blank=True),
        ),
    ]
