# Generated by Django 3.0.7 on 2020-11-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_community_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='rule',
            field=models.TextField(blank=True, null=True),
        ),
    ]
