# Generated by Django 3.0.7 on 2020-11-20 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_community_background_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='button_background_color',
            field=models.TextField(default='#30363C'),
        ),
        migrations.AddField(
            model_name='community',
            name='button_text_color',
            field=models.TextField(default='#30363C'),
        ),
        migrations.AddField(
            model_name='community',
            name='description_background_color',
            field=models.TextField(default='#30363C'),
        ),
        migrations.AddField(
            model_name='community',
            name='post_background_color',
            field=models.TextField(default='#30363C'),
        ),
        migrations.AddField(
            model_name='community',
            name='text_color',
            field=models.TextField(default='#30363C'),
        ),
        migrations.AddField(
            model_name='community',
            name='title_background_color',
            field=models.TextField(default='#30363C'),
        ),
    ]
