# Generated by Django 3.0.7 on 2020-11-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0019_auto_20201120_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='background_color',
            field=models.CharField(default='#30363C', max_length=6),
        ),
    ]
