# Generated by Django 3.0.7 on 2020-11-21 14:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0025_auto_20201121_2048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityhistory',
            name='line',
        ),
        migrations.RemoveField(
            model_name='communityhistory',
            name='role',
        ),
        migrations.AddField(
            model_name='communityhistory',
            name='new_role',
            field=models.CharField(default='MEMBER', max_length=20),
        ),
        migrations.AddField(
            model_name='communityhistory',
            name='old_role',
            field=models.CharField(default='MEMBER', max_length=20),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='MEMBER', max_length=30)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='community',
            name='member',
            field=models.ManyToManyField(blank=True, to='community.Member'),
        ),
    ]
