# Generated by Django 3.0.7 on 2020-11-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0027_auto_20201121_2125'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberinfo',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
