# Generated by Django 3.0.7 on 2020-11-22 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0028_memberinfo_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='role',
        ),
        migrations.AddField(
            model_name='memberinfo',
            name='role',
            field=models.CharField(default='MEMBER', max_length=30),
        ),
    ]
