# Generated by Django 3.0.7 on 2020-11-23 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0030_blacklisttype_communityblacklist_communityblacklistdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communityblacklistdetail',
            name='blacklist_type',
        ),
        migrations.AddField(
            model_name='communityblacklistdetail',
            name='blacklist_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.BlackListType'),
        ),
    ]
