# Generated by Django 3.0.7 on 2020-11-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0031_auto_20201123_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blacklisttype',
            name='from_timestamp',
        ),
        migrations.RemoveField(
            model_name='blacklisttype',
            name='to_timestamp',
        ),
        migrations.AddField(
            model_name='communityblacklistdetail',
            name='from_timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='communityblacklistdetail',
            name='to_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
