# Generated by Django 3.0.7 on 2020-11-26 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0032_auto_20201123_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='button_background_color',
            field=models.CharField(default='#d7dadc', max_length=7),
        ),
        migrations.AlterField(
            model_name='community',
            name='button_text_color',
            field=models.CharField(default='#1a1a1b', max_length=7),
        ),
        migrations.AlterField(
            model_name='community',
            name='description_background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='community',
            name='post_background_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
        migrations.AlterField(
            model_name='community',
            name='text_color',
            field=models.CharField(default='#000000', max_length=7),
        ),
        migrations.AlterField(
            model_name='community',
            name='title_background_color',
            field=models.CharField(default='#f5c007', max_length=7),
        ),
    ]
