# Generated by Django 3.0.7 on 2021-05-07 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0033_auto_20201127_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityhistory',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='community_history_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
