# Generated by Django 3.1.7 on 2021-03-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatv0', '0002_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
