# Generated by Django 3.0.7 on 2021-05-07 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatv0', '0006_auto_20210328_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
    ]
