# Generated by Django 3.2.3 on 2021-06-05 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatv0', '0007_auto_20210507_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='new_message',
            field=models.BooleanField(default=False),
        ),
    ]
