# Generated by Django 3.2.3 on 2021-06-06 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatv0', '0008_room_new_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='state',
            field=models.BooleanField(default=False),
        ),
    ]
