# Generated by Django 3.0.7 on 2020-11-17 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communitytrack',
            options={'ordering': ['-timestamp']},
        ),
    ]
