# Generated by Django 3.0.7 on 2020-11-17 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_community_background_color'),
        ('track', '0004_auto_20201117_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitytrack',
            name='community',
            field=models.ManyToManyField(blank=True, to='community.Community'),
        ),
    ]
