# Generated by Django 3.0.7 on 2020-11-18 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('track', '0005_auto_20201117_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='communitytrack',
            name='user',
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_track', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='track.CommunityTrack')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
