# Generated by Django 3.0.7 on 2020-11-18 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('track', '0006_auto_20201118_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='community_track',
        ),
        migrations.AddField(
            model_name='track',
            name='community_track',
            field=models.ManyToManyField(blank=True, null=True, to='track.CommunityTrack'),
        ),
        migrations.AlterField(
            model_name='track',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
