# Generated by Django 3.0.7 on 2020-11-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0018_community_background_color'),
        ('track', '0007_auto_20201118_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitytrack',
            name='community',
            field=models.ManyToManyField(blank=True, null=True, to='community.Community'),
        ),
    ]
