# Generated by Django 3.0.7 on 2020-11-20 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0010_auto_20201118_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='community_track',
            field=models.ManyToManyField(blank=True, to='track.CommunityTrack'),
        ),
    ]
