# Generated by Django 3.0.7 on 2021-03-29 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0037_auto_20201123_2125'),
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entitytype',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='notificationobject',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='post.Post'),
        ),
    ]
