# Generated by Django 3.0.7 on 2021-03-30 09:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notify', '0004_signalroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationchange',
            name='user',
        ),
        migrations.AddField(
            model_name='notificationchange',
            name='user',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
