# Generated by Django 3.0.7 on 2021-04-01 16:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0007_auto_20210401_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='entitytype',
            name='updated_At',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='usernotify',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usernotify',
            name='updated_At',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
