# Generated by Django 3.0.7 on 2021-04-02 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0033_auto_20201127_0002'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notify', '0008_auto_20210401_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityNotify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(default=0)),
                ('message', models.TextField()),
                ('community', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.Community')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
