# Generated by Django 3.0.7 on 2021-04-02 05:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0009_communitynotify'),
    ]

    operations = [
        migrations.AddField(
            model_name='communitynotify',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='communitynotify',
            name='updated_At',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
