# Generated by Django 3.0.7 on 2021-04-02 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0033_auto_20201127_0002'),
        ('notify', '0010_auto_20210402_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitynotify',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.Community'),
        ),
    ]
