# Generated by Django 3.0.7 on 2021-04-02 06:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0033_auto_20201127_0002'),
        ('notify', '0011_auto_20210402_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.AddField(
            model_name='notification',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='community.Community'),
        ),
        migrations.AddField(
            model_name='usernotify',
            name='message',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usernotify',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='_usernotify_parent_+', to='notify.UserNotify'),
        ),
    ]
