# Generated by Django 3.0.7 on 2021-04-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0012_auto_20210402_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_object',
        ),
        migrations.AddField(
            model_name='usernotify',
            name='notification_object',
            field=models.ManyToManyField(blank=True, to='notify.NotificationObject'),
        ),
    ]
