# Generated by Django 3.0.7 on 2021-04-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0013_auto_20210402_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communitynotify',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='usernotify',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
