# Generated by Django 3.0.7 on 2021-04-02 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0014_auto_20210402_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usernotify',
            name='parent',
        ),
        migrations.AddField(
            model_name='usernotify',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notify.UserNotify'),
        ),
    ]
