# Generated by Django 3.0.7 on 2021-04-03 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0015_auto_20210402_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotify',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
