# Generated by Django 3.2.3 on 2021-06-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0016_auto_20210403_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotify',
            options={'ordering': ['-created_at']},
        ),
    ]
