# Generated by Django 3.0.7 on 2021-05-15 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0016_auto_20210403_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usernotify',
            options={'ordering': ['-created_at']},
        ),
    ]
